# File: .github/workflows/repo-sync.yml

name: Sync Vue Admin

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: repo-sync PanJiaChen/vue-admin-template
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "PanJiaChen/vue-admin-template" # 源仓库
          source_branch: "master" # 源仓库分支
          destination_branch: "PanJiaChen/vue-admin-template" # 当前仓库分支
          github_token: ${{ secrets.ACCESS_TOKEN }}

      - name: repo-sync PanJiaChen/vue-element-admin
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "PanJiaChen/vue-element-admin" # 源仓库
          source_branch: "master" # 源仓库分支
          destination_branch: "PanJiaChen/vue-element-admin" # 当前仓库分支
          github_token: ${{ secrets.ACCESS_TOKEN }}
